version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14-jessie-browsers
    steps:
      - checkout # special step to check out source code to working directory
      #   - restore_cache: # special step to restore the dependency cache
      #       key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      #   - save_cache: # special step to save the dependency cache
      #       key: dependency-cache-{{ checksum "package.json" }}
      #       paths:
      #         - ./node_modules
      - run: npm test
      # - run: # run coverage report
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts: # special step to save test results as as artifact
          path: test/*.log
          prefix: test
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      - store_test_results: # special step to upload test results for display in Test Summary
          path: test/*.log
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
      - run: npx semantic-release
